### ISSUE TITLE
Views don't properly filter on multiple keys

### ISSUE THREAD

**Issue by timritzer** [couchbaselabs/walrus#19]
Views allow several filter mechanisms, including key and keys.

Walrus views do not properly support the view keys parameter, and return all data if provided with a set of keys.

The single key filtering mechanism works as expected, as does start/end key lookups for ranges.

Tested all of the above with a full CB bucket, and the filtering works as expected.

**Comment by snej** [comment]
It looks like the querying is now done in the https://github.com/couchbase/sg-bucket package, not by Walrus itself (see View.go).

**Comment by timritzer** [comment]
Thanks, I just noticed that after some digging on my own. I opened an issue on that repo.
