### ISSUE TITLE
Trouble understanding WriteUpdate()

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/walrus#6]
In `func (bucket *lolrus) WriteUpdate()`, it calls ` bucket.updateDoc()`, and according to the comments:

> Replaces a lolrusDoc as long as its sequence number hasn't changed yet.

So basically this is using a CAS loop to protect against a race where multiple goroutines are calling `WriteUpdate()` concurrently?  

Hypothetically speaking, if this mutex:

```
func (bucket *lolrus) updateDoc(k string, doc *lolrusDoc) uint64 {
	bucket.lock.Lock()
	defer bucket.lock.Unlock()
        ..
}
```

were moved up to `WriteUpdate()`, would the need to use a CAS loop update go away?  Asking not because I'm suggesting this change, but just trying to understand the problem that's being solved in `updateDoc()`

**Comment by tleyden** [comment]
@snej nevermind, I figured it out and created a [unit test](https://github.com/couchbaselabs/forestdb-bucket/blob/2cf4babd2e3b2d031278dbb31acb553875143bde/bucket_test.go#L505-L601) which proves the correct behavior.

**Comment by snej** [comment]
Sorry I didn't reply! I had my head full of Obj-C stuff and then it got lost in my inbox :(

**Comment by snej** [comment]
(The issue got lost, not my head.)

**Comment by tleyden** [comment]
Np, actually in this case it was better that you didn't reply!
